Repository Dev-FE-3/toy-project3-team2, pull requests merged in 2025-04, with the labels that each got.

#8 Feat/component-button
  src/App.tsx
  src/components/common/button.tsx
  src/components/common/guide.tsx
Labels: 🎨 Html & CSS, ✨ Feature

#1 Feat: 라우팅 및 공통 레이아웃
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icons/.gitkeep
  src/assets/icons/add.svg
  src/assets/icons/arrow-left.svg
  src/assets/icons/bookmark.svg
  src/assets/icons/fill-bookmark.svg
  src/assets/icons/fill-home.svg
  src/assets/icons/fill-user.svg
  src/assets/icons/home.svg
  src/assets/icons/logo.svg
  src/assets/icons/search.svg
  src/assets/icons/user.svg
  src/layout/.gitkeep
  src/layout/Header.tsx
  src/layout/Layout.tsx
  src/layout/NavBar.tsx
  src/pages/.gitkeep
  src/pages/EditProfile.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/PlaylistCreate.tsx
  src/pages/PlaylistDetail.tsx
  src/pages/Signup.tsx
  src/pages/Subscriptions.tsx
  src/styles/App.css
  src/styles/index.css
Labels: 🎨 Html & CSS, ✨ Feature, 🖥️ Front-end

#13 Feat/component input
  src/App.tsx
  src/assets/icons/eye-crossed-muted.svg
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/common/guide.tsx
  src/pages/Guide.tsx
Labels: 🎨 Html & CSS, ✨ Feature

#14 Feat : 공통 컴포넌트 - OverflowMenu
  package-lock.json
  src/components/common/OverflowMenu.tsx
  src/pages/Guide.tsx
  src/pages/MyPage.tsx
  vite.config.ts
Labels: 🎨 Html & CSS, ✨ Feature, 🖥️ Front-end

#18 Refactor: 디자인 가이드 페이지 정리 및 레이아웃 구조 개선
  src/components/common/PlaylistCard.tsx
  src/layout/Header.tsx
  src/layout/Layout.tsx
  src/pages/Guide.tsx
Labels: 🎨 Html & CSS, 🔨 Refactoring, 🖥️ Front-end

#20 Feat: 공통 컴포넌트 input 수정
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/pages/Guide.tsx
Labels: 🐞 bug, 🖥️ Front-end

#22 Feat: PlaylistCard 구조 정리 및 상세 페이지 이동 기능 추가
  package-lock.json
  package.json
  src/components/common/PlaylistCard.tsx
  src/pages/Guide.tsx
  tailwind.config.js
Labels: ✨ Feature, 🔨 Refactoring, 🖥️ Front-end

#21 Design: 플레이리스트 생성 페이지 퍼블리싱
  package-lock.json
  src/components/Toggle.tsx
  src/components/common/.gitkeep
  src/pages/Guide.tsx
  src/pages/PlaylistCreate.tsx
Labels: 🎨 Html & CSS, ✨ Feature, 🖥️ Front-end

#24 Feat: Supabase 스키마 기반 TypeScript 타입 정의 추가
  src/types/.gitkeep
  src/types/comment.ts
  src/types/playlist.ts
  src/types/user.ts
  src/types/video.ts
Labels: ✨ Feature

#23 Design: 로그인, 회원가입 페이지 퍼블리싱
  src/assets/icons/error.svg
  src/assets/icons/success.svg
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: 🎨 Html & CSS, 🖥️ Front-end

#25 Feat: 마이페이지, 정보수정 퍼블리싱
  src/assets/icons/arrow-bottom.svg
  src/assets/icons/camera.svg
  src/components/DropDownMenu.tsx
  src/components/common/OverflowMenu.tsx
  src/layout/Header.tsx
  src/pages/EditProfile.tsx
  src/pages/Guide.tsx
  src/pages/MyPage.tsx
  src/services/.gitkeep
Labels: 🎨 Html & CSS, 🖥️ Front-end

#27 Design: 헤더 스타일 수정
  package-lock.json
  src/layout/Header.tsx
Labels: 🎨 Html & CSS

#26 Design: 플레이리스트 상세 - 상단 플레이어 영역 퍼블리싱
  src/components/common/PlaylistCard.tsx
  src/components/playlistDetail/Player.tsx
  src/components/playlistDetail/Videos.tsx
  src/pages/PlaylistDetail.tsx
  src/styles/index.css
Labels: 🎨 Html & CSS, 🖥️ Front-end

#29 Feat: 로그인/회원가입 supabase연동
  package-lock.json
  src/components/common/Input.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: ✨ Feature, 🖥️ Front-end

#35 Design: 헤더 사이즈 고정
  src/layout/Header.tsx
  src/layout/Layout.tsx
Labels: 🎨 Html & CSS, 🖥️ Front-end

#32 Feat: 유튜브 메타데이터 연동
  src/assets/icons/video_delete.svg
  src/components/playlistCreate/Toggle.tsx
  src/components/playlistCreate/VideoCard.tsx
  src/pages/PlaylistCreate.tsx
  src/utils/getYoutubeMeta.ts
Labels: ✨ Feature

#42 Design: Outlet 스크롤 추가
  src/layout/Header.tsx
  src/layout/Layout.tsx
Labels: 🎨 Html & CSS, 🖥️ Front-end

#41 Style: 비공개 아이콘 추가 시 제목 정렬 스타일 수정
  src/components/common/PlaylistCard.tsx
Labels: 🎨 Html & CSS, 🖥️ Front-end

#46 Refactor: route 분리
  src/App.tsx
  src/routes/index.tsx
Labels: 🔨 Refactoring

#49 Refactor: id를 playlistId로 변경하고 description 길이 상수를 상단으로 분리
  src/components/playlistDetail/Player.tsx
  src/hooks/usePlaylistDetail.ts
  src/pages/PlaylistDetail.tsx
Labels: 🔨 Refactoring, 🖥️ Front-end

#48 Feat: ErrorPage 구현 및 라우트 연결
  src/assets/icons/broken-not.svg
  src/components/common/Error.tsx
  src/pages/ErrorPage.tsx
  src/routes/index.tsx
Labels: 🎨 Html & CSS, ✨ Feature, 🖥️ Front-end

#45 Feat: 댓글 기능 구현
  src/App.tsx
  src/assets/icons/broken-not.svg
  src/assets/icons/video_delete.svg
  src/assets/imgs/profile-image-default.svg
  src/components/common/Error.tsx
  src/components/common/OverflowMenu.tsx
  src/components/common/PlaylistCard.tsx
  src/components/myPage/DropDownMenu.tsx
  src/components/playlistCreate/Toggle.tsx
  src/components/playlistCreate/VideoCard.tsx
  src/components/playlistDetail/Comments.tsx
  src/layout/Header.tsx
  src/layout/Layout.tsx
  src/pages/EditProfile.tsx
  src/pages/ErrorPage.tsx
  src/pages/MyPage.tsx
  src/pages/PlaylistCreate.tsx
  src/pages/PlaylistDetail.tsx
  src/routes/index.tsx
  src/services/axios/axiosInstance.ts
  src/services/supabase/supabaseClient.ts
  src/store/.gitkeep
  src/store/useUserStore.ts
  src/types/comment.ts
  src/utils/getYoutubeMeta.ts
Labels: ✨ Feature, 🖥️ Front-end

#53 Feat: 플레이리스트 상세페이지 스켈레톤 UI 추가
  src/components/playlistDetail/Player.tsx
  src/components/playlistDetail/Videos.tsx
  src/components/playlistDetail/playlistSkeleton.tsx
  src/pages/PlaylistDetail.tsx
Labels: ✨ Feature, 🖥️ Front-end

#55 Feat: PlaylistDetail 기능 1차 완성
  src/App.tsx
  src/components/playlistDetail/Comments.tsx
  src/components/playlistDetail/Player.tsx
  src/components/playlistDetail/Videos.tsx
  src/components/playlistDetail/playlistSkeleton.tsx
  src/hooks/.gitkeep
  src/hooks/usePlaylistDetail.ts
  src/pages/Guide.tsx
  src/pages/PlaylistDetail.tsx
  src/types/comment.ts
  src/types/playlist.ts
  src/utils/formatData.ts
Labels: ✨ Feature, 🖥️ Front-end

#54 Chore: 절대경로 설정
  src/pages/PlaylistCreate.tsx
  src/routes/index.tsx
  tsconfig.app.json
  tsconfig.json
  vite.config.ts
Labels: 🔨 Refactoring

#73 Feat: 플레이리스트 상세 페이지 Skeleton UI 적용
  src/components/common/skeleton.tsx
  src/components/playlistDetail/CommentSkeleton.tsx
  src/components/playlistDetail/Comments.tsx
  src/components/playlistDetail/playlistSkeleton.tsx
Labels: ✨ Feature, 🖥️ Front-end

#72 Feat: 로그인 회원가입 추가 기능 구현
  src/pages/Login.tsx
  src/pages/Signup.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/index.tsx
Labels: ✨ Feature, 🔨 Refactoring, 🖥️ Front-end

#52 Feat: 마이페이지, 정보수정 기능 구현
  src/App.tsx
  src/components/common/PlaylistCard.tsx
  src/layout/Header.tsx
  src/layout/NavBar.tsx
  src/pages/EditProfile.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/Signup.tsx
  src/routes/index.tsx
  src/services/axios/axiosInstance.ts
  src/services/supabase/supabaseClient.ts
  src/services/supabase/uploadProfileImage.ts
  src/store/useUserStore.ts
Labels: ✨ Feature, 🖥️ Front-end

#70 Feat: 플레이리스트 생성 기능 구현
  src/components/common/Input.tsx
  src/components/playlistDetail/Comments.tsx
  src/pages/PlaylistCreate.tsx
  src/services/axios/axiosInstance.ts
Labels: ✨ Feature, 🖥️ Front-end

#81 Fix: playlistCard 썸네일 비율 수정
  src/components/common/PlaylistCard.tsx
  src/components/playlistDetail/Comments.tsx
Labels: 🎨 Html & CSS, 선택

#89 Feat: 플레이리스트 상세페이지 추가 기능 구현
  src/components/playlistDetail/Player.tsx
  src/layout/Header.tsx
Labels: ✨ Feature, 🖥️ Front-end

#87 Feat: 업데이트순으로 변경
  src/components/myPage/DropDownMenu.tsx
  src/pages/MyPage.tsx
Labels: ✨ Feature, 🖥️ Front-end

#86 Feat: 목록페이지 상태관리
  src/hooks/usePlaylistSearch.ts
  src/hooks/usePlaylists.ts
  src/pages/Guide.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
  src/pages/Subscriptions.tsx
  src/routes/ProtectedRoute.tsx
Labels: ✨ Feature, 🔨 Refactoring, 🖥️ Front-end

#90 Fix: user id 패칭을 위한 타입 및 API 응답 구조 수정
  src/hooks/usePlaylistDetail.ts
  src/layout/Header.tsx
  src/pages/PlaylistCreate.tsx
  src/types/playlist.ts
Labels: 🔨 Refactoring, 🖥️ Front-end

#84 Feat: 마이페이지, 정보수정 페이지
  src/components/common/TextArea.tsx
  src/pages/EditProfile.tsx
  src/pages/MyPage.tsx
Labels: ✨ Feature, 🔨 Refactoring, 🖥️ Front-end

#83 Feat: 수정 페이지 기능 구현
  src/components/common/PlaylistCard.tsx
  src/components/playlistCreate/VideoCard.tsx
  src/hooks/usePlaylistDetail.ts
  src/layout/Header.tsx
  src/pages/PlaylistCreate.tsx
  src/pages/PlaylistDetail.tsx
  src/routes/index.tsx
  src/types/video.ts
  src/utils/video.tsx
Labels: ✨ Feature

#91 Refactor: 생성 및 수정 페이지 수정
  src/pages/PlaylistCreate.tsx
Labels: 🐞 bug, 🖥️ Front-end

#97 Fix: 오버플로우 메뉴 페이지 이동시 닫히도록 수정
  src/components/common/OverflowMenu.tsx
Labels: 🐞 bug, 🖥️ Front-end

#96 Feat: 마이페이지 플레이리스트 목록 조건 추가
  src/layout/Header.tsx
  src/pages/MyPage.tsx
Labels: ✨ Feature, 🖥️ Front-end

#99 Fix: 내가 만든 플레이리스트인지 확인하는 로직 수정
  src/components/common/PlaylistCard.tsx
  src/layout/Header.tsx
  src/pages/PlaylistCreate.tsx
Labels: 🐞 bug, 🖥️ Front-end

#103 Fix: params 로직 수정
  src/layout/Header.tsx
Labels: 🐞 bug, 🖥️ Front-end

#95 Feat: 로그인 회원가입 수정
  src/pages/Login.tsx
  src/pages/Signup.tsx
  src/routes/index.tsx
Labels: 🔨 Refactoring, 🖥️ Front-end

#106 Refactor: 프로필 디폴트 이미지 중복 제거
  src/pages/EditProfile.tsx
  src/pages/MyPage.tsx
Labels: 🔨 Refactoring, 🖥️ Front-end

#102 Feat: 댓글 카운트 표시 및 실시간 업데이트
  src/components/common/PlaylistAction.tsx
  src/components/common/PlaylistCard.tsx
  src/components/playlistDetail/Comments.tsx
  src/components/playlistDetail/Player.tsx
Labels: ✨ Feature, 🖥️ Front-end

#93 Feat: 무한로딩
  src/hooks/useInfiniteScroll.ts
  src/hooks/usePlaylists.ts
  src/pages/Home.tsx
  src/pages/Subscriptions.tsx
Labels: ✨ Feature, 🖥️ Front-end

#104 Refactor: 정보수정 유효성 검사 방식 통일
  src/pages/EditProfile.tsx
Labels: ✨ Feature, 🔨 Refactoring, 🖥️ Front-end

#100 Feat: playlistAction 컴포넌트에 구독/좋아요 상태 업데이트 구현
  src/components/common/PlaylistAction.tsx
  src/components/playlistDetail/Player.tsx
  src/hooks/usePlaylistDetail.ts
Labels: ✨ Feature, 🖥️ Front-end, 필수

#111 Feat: 플레이리스트 상세 페이지에서 플레이리스트 삭제 기능 구현
  src/components/common/PlaylistCard.tsx
  src/components/playlistDetail/CommentSkeleton.tsx
  src/components/playlistDetail/Player.tsx
  src/components/playlistDetail/Videos.tsx
  src/components/playlistDetail/playlistSkeleton.tsx
  src/layout/Header.tsx
  src/pages/MyPage.tsx
  src/pages/PlaylistDetail.tsx
  src/types/video.ts
Labels: ✨ Feature, 🖥️ Front-end, 필수

#109 Feat : 목록 페이지 정렬
  src/components/common/PlaylistAction.tsx
  src/components/common/PlaylistCard.tsx
  src/components/playlistDetail/Player.tsx
  src/hooks/usePlaylistDetail.ts
  src/hooks/usePlaylists.ts
  src/pages/Home.tsx
  src/pages/PlaylistDetail.tsx
  src/pages/Subscriptions.tsx
Labels: ✨ Feature, 🖥️ Front-end

#117 Feat: 플레이리스트 생성 제목, 소개글 최대 길이 제한
  src/pages/PlaylistCreate.tsx
Labels: ✨ Feature, 🖥️ Front-end

#116 Refactor: Video id type optional로 수정
  src/types/video.ts
Labels: 🐞 bug

#120 Feat: 댓글 등록 시 enter 가능
  src/components/playlistDetail/Comments.tsx
Labels: ✨ Feature, 🖥️ Front-end

#122 Fix: 플레이리스트 수정 시 header 내 title이 반영되도록 dependency 추가
  src/layout/Header.tsx
Labels: 🐞 bug, 🖥️ Front-end

#124 Feat: 파비콘 및 페이지 타이틀 수정
  favicon.ico
  favicon.png
  index.html
Labels: 🖥️ Front-end, 선택

#125 Chore: 모든 파일에 prettier 적용
  .github/ISSUE_TEMPLATE/✅-issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierrc
  README.md
  components.json
  eslint.config.js
  playwright.config.ts
  postcss.config.js
  src/components/common/PlaylistAction.tsx
  src/components/common/PlaylistCard.tsx
  src/components/playlistDetail/Player.tsx
  src/hooks/usePlaylistDetail.ts
  src/pages/Guide.tsx
  src/pages/PlaylistCreate.tsx
  src/routes/index.tsx
  src/utils/shadcn.ts
  tailwind.config.js
  tests-examples/demo-todo-app.spec.ts
  tests/example.spec.ts
Labels: 🔨 Refactoring

#128 Chore: import/order eslint 설정 및 적용
  eslint.config.js
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/Button.tsx
  src/components/common/Error.tsx
  src/components/common/Input.tsx
  src/components/common/OverflowMenu.tsx
  src/components/common/PlaylistAction.tsx
  src/components/common/PlaylistCard.tsx
  src/components/common/SearchBar.tsx
  src/components/common/TextArea.tsx
  src/components/myPage/DropDownMenu.tsx
  src/components/playlistDetail/Comments.tsx
  src/components/playlistDetail/Player.tsx
  src/hooks/usePlaylistDetail.ts
  src/hooks/usePlaylists.ts
  src/layout/Header.tsx
  src/layout/Layout.tsx
  src/layout/NavBar.tsx
  src/main.tsx
  src/pages/EditProfile.tsx
  src/pages/Guide.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/PlaylistCreate.tsx
  src/pages/PlaylistDetail.tsx
  src/pages/Signup.tsx
  src/pages/Subscriptions.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/index.tsx
  src/services/axios/axiosInstance.ts
  src/store/useUserStore.ts
  vite.config.ts
Labels: 🔨 Refactoring

#129 Fix: 정보수정 데이터 초기값 설정 수정
  src/pages/EditProfile.tsx
Labels: 🐞 bug, 🖥️ Front-end

#132 Feat: 마이페이지 무한로딩 기능 추가
  src/hooks/useUserPlaylists.ts
  src/pages/MyPage.tsx
Labels: ✨ Feature, 🖥️ Front-end, 필수

#127 Fix: 검색기능
  src/components/common/SearchBar.tsx
  src/hooks/usePlaylists.ts
  src/pages/Home.tsx
  src/pages/Subscriptions.tsx
Labels: 🐞 bug, ✨ Feature, 🖥️ Front-end

#133 Feat: 마이페이지 구독순, 좋아요순 정렬 추가
  src/components/myPage/DropDownMenu.tsx
  src/hooks/useUserPlaylists.ts
  src/pages/MyPage.tsx
Labels: ✨ Feature, 🖥️ Front-end, 필수

#134 Feat: 마이페이지, 정보수정 소개글 수정
  src/pages/EditProfile.tsx
  src/pages/MyPage.tsx
Labels: 🎨 Html & CSS, ✨ Feature, 🖥️ Front-end, 선택

#135 Style: 전체 페이지 절대경로 적용
  src/components/common/Button.tsx
  src/components/common/Error.tsx
  src/components/common/Input.tsx
  src/components/common/OverflowMenu.tsx
  src/components/common/SearchBar.tsx
  src/components/common/TextArea.tsx
  src/components/common/skeleton.tsx
  src/components/myPage/DropDownMenu.tsx
  src/components/playlistCreate/VideoCard.tsx
  src/components/playlistDetail/Comments.tsx
  src/hooks/usePlaylistDetail.ts
  src/layout/NavBar.tsx
  src/pages/EditProfile.tsx
  src/pages/ErrorPage.tsx
  src/pages/MyPage.tsx
  src/services/axios/axiosInstance.ts
  src/store/useUserStore.ts
Labels: 🔨 Refactoring, 🖥️ Front-end, 선택

#136 Feat: 무한로딩 지연
  src/pages/Home.tsx
  src/pages/Subscriptions.tsx
Labels: 🔨 Refactoring, 🖥️ Front-end, 선택

#150 Feat: 플레이리스트 없는 경우 UI 구현
  src/assets/icons/broken-note.svg
  src/components/common/Error.tsx
  src/components/common/PlaylistEmpty.tsx
  src/pages/MyPage.tsx
Labels: ✨ Feature, 🖥️ Front-end

#148 Feat: 추천페이지 정렬, 데이터 개수 수정
  src/hooks/usePlaylistSearch.ts
  src/hooks/usePlaylists.ts
  src/hooks/useUserPlaylists.ts
  src/layout/Header.tsx
  src/pages/Home.tsx
  src/pages/MyPage.tsx
Labels: ✨ Feature, 🔨 Refactoring, 🖥️ Front-end

#151 Feat: 유효성 문구 통일, 이메일 유효성 검사
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: 🔨 Refactoring, 🖥️ Front-end, 선택

#144 Feat: react-toastify로 토스트 팝업 구현
  package-lock.json
  package.json
  src/App.tsx
  src/layout/Header.tsx
  src/pages/EditProfile.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/PlaylistCreate.tsx
  src/pages/Signup.tsx
  src/styles/index.css
  src/utils/toast.ts
Labels: 🎨 Html & CSS, ✨ Feature, 🖥️ Front-end, 선택

#152 Feat: 마이페이지 소개글 300자 제한으로 변경
  src/pages/EditProfile.tsx
Labels: 🖥️ Front-end

#154 Design: toast 디자인 적용
  src/App.tsx
  src/layout/Header.tsx
  src/pages/MyPage.tsx
  src/pages/Signup.tsx
  src/utils/toast.ts
Labels: 🎨 Html & CSS, 🖥️ Front-end

#162 Fix: 헤더 제거 검색기능 수정
  src/layout/Header.tsx
  src/layout/Layout.tsx
  src/pages/Home.tsx
  src/pages/Subscriptions.tsx
  src/store/useSearchStore.ts
Labels: 🐞 bug, 🖥️ Front-end

#163 Chore/test
  .gitignore
  playwright.config.ts
  tests-examples/demo-todo-app.spec.ts
Labels: ✅ Test

#165 Refactor: console.log, alert 삭제, 에러 처리 통일화
  src/components/playlistDetail/Player.tsx
  src/layout/Header.tsx
  src/pages/EditProfile.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/Signup.tsx
  src/utils/getYoutubeMeta.ts
Labels: 🔨 Refactoring

#157 Test: 플레이리스트 생성 시나리오 테스트 코드 작성
  package-lock.json
  package.json
  src/components/playlistCreate/VideoCard.tsx
  src/pages/PlaylistCreate.tsx
  tests/auth.test.ts
  tests/example.spec.ts
  tests/login-setup.ts
  tests/playlist-create.spec.ts
Labels: ✅ Test

#155 Test: login setup 파일 생성, 로그인 확인
  tests/login-setup.ts
Labels: ✨ Feature, 🖥️ Front-end, ✅ Test

#159 Test: login 테스트 코드
  src/pages/Login.tsx
  src/pages/Signup.tsx
  tests/login.spec.ts
Labels: 🖥️ Front-end, ✅ Test

#160 Test: 마이페이지 로그아웃 테스트
  src/components/common/OverflowMenu.tsx
  src/layout/Header.tsx
  tests/login-setup.ts
  tests/setup/logout.spec.ts
Labels: ✅ Test

#166 Rename: logout.spec.ts 파일 위치 이동
  tests/auth.test.ts
  tests/logout.spec.ts
Labels: 🔨 Refactoring, ✅ Test

#169 Test: 테스트 코드 형식 통일
  src/components/common/OverflowMenu.tsx
  src/layout/Header.tsx
  tests/logout.spec.ts
Labels: ✅ Test

#167 Test: 플레이리스트 액션 테스트
  src/components/common/PlaylistAction.tsx
  tests/playlist-action.spec.ts
Labels: ✅ Test

#168 Fix: 로그인 셋업/테스트 파일 병합
  tests/login-setup.ts
  tests/login.spec.ts
Labels: 🐞 bug, ✅ Test

#164 Refactor: API 호출 로직과 tanstack-query hook 분리
  src/api/comment.ts
  src/api/playlist.ts
  src/components/playlistDetail/Comments.tsx
  src/hooks/queries/useGetCommentQuery.ts
  src/hooks/queries/usePlaylistMutation.ts
  src/hooks/queries/usePostCommentMutation.ts
  src/layout/Header.tsx
  src/pages/PlaylistCreate.tsx
  src/types/comment.ts
  src/types/playlist.ts
Labels: 🔨 Refactoring

#170 Fix: 훅 호출 위치 수정
  src/pages/PlaylistCreate.tsx
Labels: 🐞 bug

#171 Fix: 중복 코드 제거
  src/pages/PlaylistCreate.tsx
Labels: 🐞 bug

#173 Feat: 구독 수 실시간 동기화
  src/components/common/PlaylistAction.tsx
Labels: ✨ Feature, 🖥️ Front-end

#177 Fix: 마이페이지 드롭다운메뉴 옵션명 바뀌지 않는 이슈
  src/components/myPage/DropDownMenu.tsx
  src/constants/.gitkeep
  src/constants/dropDownMenuOptions.ts
  src/pages/MyPage.tsx
Labels: 🐞 bug, 🖥️ Front-end

#175 Feat: 삭제 모달 구현
  src/components/common/ModalDelete.tsx
  src/components/common/PlaylistCard.tsx
  src/layout/Header.tsx
Labels: ✨ Feature, 🖥️ Front-end, 선택

#178 Refactor: 마이페이지 코드 분리
  src/api/playlist.ts
  src/api/user.ts
  src/components/myPage/UserPlaylistSection.tsx
  src/components/myPage/UserProfileSection.tsx
  src/hooks/queries/usePlaylistMutation.ts
  src/hooks/queries/useUserInfoQuery.ts
  src/hooks/queries/useUserPlaylistsQuery.ts
  src/hooks/useUserPlaylists.ts
  src/pages/MyPage.tsx
  src/types/playlist.ts
Labels: 🔨 Refactoring

#181 Docs: README.md 작성
  README.md
Labels: Docs

#183 Refactor: 마이페이지/정보수정 코드 리뷰 반영 및 컴포넌트 분리
  src/api/user.ts
  src/components/common/OverflowMenu.tsx
  src/components/editProfile/DescriptionField.tsx
  src/components/editProfile/NicknameField.tsx
  src/components/editProfile/PasswordField.tsx
  src/components/editProfile/ProfileImage.tsx
  src/hooks/queries/useNicknameCheckMutation.ts
  src/hooks/queries/usePlaylistMutation.ts
  src/hooks/queries/useUpdateProfileMutation.ts
  src/hooks/queries/useUserInfoQuery.ts
  src/hooks/queries/useUserPlaylistsQuery.ts
  src/hooks/useOnClickOutside.ts
  src/hooks/useUserPlaylists.ts
  src/pages/EditProfile.tsx
  src/utils/validation.ts
Labels: 🔨 Refactoring

#184 Refactor: 코드 리뷰 반영 및 UX 개선
  src/components/common/PlaylistAction.tsx
  src/components/playlistDetail/Player.tsx
  src/components/playlistDetail/Videos.tsx
  src/hooks/queries/usePlaylistActionInfoQuery.ts
  src/hooks/queries/usePlaylistDetailQuery.ts
  src/layout/Header.tsx
  src/pages/PlaylistCreate.tsx
  src/pages/PlaylistDetail.tsx
  src/utils/getEmbedUrl.ts
  tests/playlist-action.spec.ts
Labels: 🔨 Refactoring

#185 Refactor: 코드리뷰 반영, 추가 리팩토링
  package-lock.json
  package.json
  src/components/common/Input.tsx
  src/components/common/SearchBar.tsx
  src/components/common/ValidationMessage.tsx
  src/components/listPage/ListpageSkeleton.tsx
  src/components/listPage/PlaylistList.tsx
  src/constants/signupError.ts
  src/hooks/queries/usePlaylistsQuery.ts
  src/hooks/useInfiniteScrollHandler.ts
  src/layout/Layout.tsx
  src/pages/Guide.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
  src/pages/Subscriptions.tsx
  src/types/playlist.ts
  src/utils/validation.ts
Labels: 🔨 Refactoring, 🖥️ Front-end
